ignore:
  - "src/main/java/edu/fiuba/HorizonProject/controlador"
  - "src/main/java/edu/fiuba/HorizonProject/vista"
  - "src/main/java/edu/fiuba/HorizonProject/App.java"
  - "src/main/java/edu/fiuba/HorizonProject/Main.java"
  - "src/main/java/edu/fiuba/HorizonProject/SystemInfo.java"
