ignore:
  - "src/main/java/edu/fiuba/HorizonProyect/controlador"
  - "src/main/java/edu/fiuba/HorizonProyect/vista"
  - "src/main/java/edu/fiuba/HorizonProyect/App.java"
  - "src/main/java/edu/fiuba/HorizonProyect/Main.java"
  - "src/main/java/edu/fiuba/HorizonProyect/SystemInfo.java"
